#!/bin/bash

# Script to clear the "pending" flag on a newly imported module

BINDIR=/home/admin/bin/git

. $BINDIR/functions

if [ $# != 1 ] ; then
   echo "Too many arguments" 1>&2
   echo "Usage: finish-import <repository-name>" 1>&2
   exit 1
fi

validate_repository_name "$1"
name="$1"

export GIT_DIR=/git/$name.git

if ! [ -e $GIT_DIR/pending ] ; then
    echo 1>&2 "'$name' is not a Git repository that is currently being imported"
    exit 1
fi

if [ -e $GIT_DIR/gnome_doap ] ; then
    $BINDIR/validate-doap "$name" < $GIT_DIR/gnome_doap
    if [ $? -gt 0 ]; then
        echo ERROR: Cannot clear pending flag as DOAP syntax is invalid >&2
        exit 1
    fi
fi

echo "Clearing pending flag on $GIT_DIR"
rm $GIT_DIR/pending

$BINDIR/update-cgit

echo "$name is now ready for use"
