#!/usr/bin/python

# This checks to see if an update is an update that the automated
# translations user is allowed to do. This user is used by l10n.gnome.org.
#
# The per-repository git config keys
#
#  hooks.po-directories (default 'po')
#  hooks.help-directories (default 'help')
#
# Define the directories that have po-file or translated help structure.

import re
import os
import sys
from git import *

def error(msg):
    print >>sys.stderr, msg
    sys.exit(1)

def config_dirs(key, default):
    try:
        raw = git.config("key", _quiet=True)
    except CalledProcessError:
        raw = default

    return [os.path.normpath(p) for p in raw.split()]

def relative_path(path, base):
    if path.startswith(base + '/'):
        return path[len(base) + 1:]
    else:
        return None

def check_translations(oldrev, newrev, refname):
    if not refname.startswith('refs/heads/'):
        error("translations user can only update branches")

    if re.match(r'^0+$', oldrev):
        error("translations user cannot create branches")

    if re.match(r'^0+$', newrev):
        error("translations user cannot delete branches")

    po_directories = config_dirs('hooks.po-directories', 'po')
    help_directories = config_dirs('hooks.help-directories', 'help')

    # Iterate through all changed files.  Passing -z to git diff-tree
    # gives a result with separation by NUL characters, avoiding
    # having to deal with quoting. NUL separates the meta-information
    # from the pathname and from the next entry
    lines = git.diff_tree(oldrev, newrev, z=True, r=True).split('\0')
    for i in xrange(0, len(lines) - 1, 2):
        srcmode, destmode, srcsha, destsha, status = lines[i].split()
        path = lines[i + 1]

        ok = False
        for dir in po_directories:
            relpath = relative_path(path, dir)
            if relpath is None:
                continue

            # Arbitrary change to a .po file
            if re.match(r'^[a-zA-Z@_]+.po$', relpath):
                ok = True

            # Arbitrary change to LINGUAS
            if relpath == 'LINGUAS':
                ok = True

        for dir in help_directories:
            relpath = relative_path(path, dir)
            if relpath is None:
                continue

            # Arbitrary change to a .po file in a language subdir
            if re.match(r'^[a-zA-Z@_]+/[a-zA-Z@_]+.po$', relpath):
                ok = True
            # Arbitrary change to a PNG in the figures/ directory
            elif re.match(r'^[a-zA-Z@_]+/figures/[a-zA-Z0-9_-].png$', relpath):
                ok = True
            # Very limited changes to <help-dir>/Makefile.am
            elif relpath == 'Makefile.am':
                if status != 'M':
                    error("translations user cannot modify '%s' in this way" % path)

                diff = git.diff(oldrev + ':' + path, newrev + ':' + path).split('\n')

                in_header = True
                for line in diff:
                    # Ignore anything up to the first @@
                    if line.startswith('@@'):
                        in_header = False
                    if in_header:
                        continue

                    # Changes in a diff are line that begin with a '+' or '-' character
                    if not re.match(r'^[-+]', line):
                        continue

                    # The only changes that we allow are changes that add or delete a
                    # DOC_LINGUAS line we understand and validate against a strict
                    # pattern. All other changes are forbidden.
                    if not re.match(r'^[-+]DOC_LINGUAS *= *([a-zA-Z@_]+( +|$))*$', line):
                        error("translations user cannot modify '%s' in this way" % path)

                ok = True

        if not ok:
            error("translations user cannot modify '%s'" % path)

if len(sys.argv) == 4:
    check_translations(*sys.argv[1:])
else:
    for line in sys.stdin:
        check_translations(line.split())
