#!/usr/bin/python
import ldap
import grp
import os
import sys
import shutil
import subprocess

## first you must open a connection to the server
try:
    l = ldap.open("ldap-back")
    l.simple_bind("cn=Manager,dc=gnome,dc=org")
except ldap.LDAPError, e:
    print e
    sys.exit(1)


def get_uids_from_group(group):
    filter = "(cn=%s)" % group
    try:
        ldap_result_id = l.search ("ou=groups,dc=gnome,dc=org",
                                   ldap.SCOPE_SUBTREE, filter, None)
        while 1:
            result_type, group_data = l.result(ldap_result_id, 0)
            if (group_data == []):
                break
            else:
                group_info = group_data[0][1]
                return group_info['memberUid']
    except ldap.LDAPError, e:
        print e
        sys.exit(1)

    return {}


def create_home_directory (uid):
    src = '/etc/skel'
    dst = "/home/users/%s" % uid
    if os.path.isdir("/home/users/%s" % uid):
        return

    shutil.copytree(src, dst, True)
    subprocess.call(['/bin/chown', '-R', '%s:%s' % (uid, uid), dst ])
    print "Created home directory for '%s'" % uid

    return


if __name__ == '__main__':
    # Get our list of ftpadmin members
    user_list = get_uids_from_group ("ftpadmin")
    for user in user_list:
        create_home_directory (user)
    user_list = get_uids_from_group ("gnomeweb")
    for user in user_list:
        create_home_directory (user)
    user_list = get_uids_from_group ("gnomecvs")
    for user in user_list:
        create_home_directory (user)

