#!/bin/bash

# Script to create a new repository

# NOTE: This script is run via sudo to the gitadmin user. Using sudo constrains
#  the environment, but it's important to do validation on the argument and
#  be careful how we use it.

BINDIR=/home/admin/gitadmin-bin

. $BINDIR/functions

validate_repository_name "$1"
name="$1"

if [ -e /git/$name.git -o -e /git/preview/$name.git ] ; then
   echo "'$name' already exists" 1>&2
   exit 1
fi

if [ -e /mnt/git-data/svn-archive/$name ] ; then
   echo "'$name' already exists as an archived project" 1>&2
   exit 1
fi

export GIT_DIR=/git/$name.git
git init --shared --bare
chgrp -R gnomecvs $GIT_DIR
$BINDIR/gnomify-repos $GIT_DIR

# Mark as a "pending" repository
touch $GIT_DIR/pending

$BINDIR/update-cgit

user=$SUDO_USER
if [ -z "$user" ] ; then
    user=$USER
fi

echo <<EOF
You can now import an existing Git repository using:

  git push ssh://$user@git.gnome.org/git/$name refs/heads/* refs/tags/*

When you are finished importing and everything looks good, run:

  ssh git.gnome.org finish-import $name
EOF
