#!/bin/bash

# Script to clear the "pending" flag on a newly imported module

BINDIR=/home/admin/gitadmin-bin

. $BINDIR/functions

validate_repository_name "$1"
name="$1"

export GIT_DIR=/git/$name.git

if ! [ -e $GIT_DIR/pending ] ; then
    echo 1>&2 "'$name' is not a Git repository that is currently being imported"
    exit 1
fi

echo "Clearing pending flag on $GIT_DIR"
rm $GIT_DIR/pending

$BINDIR/update-cgit

echo "$name is now ready for use"
