#!/bin/bash

in_gitadmin=false
for g in `groups` ; do
    if [ $g = 'gitadmin' -o $g = 'sysadmin' ] ; then
	in_gitadmin=true
    fi
done

if ! $in_gitadmin ; then
    echo 1>&2 "You must be in the gitadmin group to force a push"
    echo 1>&2 "Please contact contact gitmaster@gnome.org for assistance"
    exit 1
fi

export GNOME_GIT_FORCE=1
exec git-receive-pack "$@"
