#!/usr/bin/python

import os
import shlex

# vim: set ts=4 sw=4:

# In case .bashrc was executed, umask might have been changed from
# the default, which could result in files being created private
# not world-readable
os.umask(0002)

def rungitcommand(args):
    cmds = {
        'create-repository': '/home/admin/bin/git/create-repository',
        'finish-import': '/home/admin/bin/git/finish-import',
        # These allow 'git push --exec=force/import'
        'force': '/home/admin/bin/git/receive-pack-force',
        'import': '/home/admin/bin/git/receive-pack-import',
    }

    if args[0] in cmds:
        cmd = [cmds[args[0]]]
        cmd.extend(args[1:])
    else:
        cmd = ['/usr/bin/git-shell', '-c', os.environ['SSH_ORIGINAL_COMMAND']]

    os.execv(cmd[0], cmd)


if __name__ == "__main__":
    if 'SSH_ORIGINAL_COMMAND' in os.environ:
        rungitcommand(shlex.split(os.environ['SSH_ORIGINAL_COMMAND']))
    else:
        import sys
        print >>sys.stderr, 'SSH authentication succeeded. Interactive login is not allowed.'
        sys.exit(1)
