#!/bin/bash

# vim: set ts=4 sw=4:

# In case .bashrc was executed, umask might have been changed from
# the default, which could result in files being created private
# not world-readable
umask 0002

rungitcommand () {
    COMMAND=$1
    shift

    case "$COMMAND" in
	create-repository)
	    exec /home/admin/gitadmin-bin/create-repository "$@"
	    ;;

	finish-import)
	    exec /home/admin/gitadmin-bin/finish-import "$@"
	    ;;

	# These allow 'git push --exec=force/import'
	force)
	    exec /home/admin/gitadmin-bin/receive-pack-force "$@"
	    ;;

	import)
	    exec /home/admin/gitadmin-bin/receive-pack-import "$@"
	    ;;

	*)
	    exec /usr/bin/git-shell -c "$SSH_ORIGINAL_COMMAND"
	    ;;
    esac
}

if [ "$SSH_ORIGINAL_COMMAND" != "" ]; then
    # $SSH_ORIGINAL_COMMAND has quoting; split it apart into arguments
    # by not quoting the variable
    rungitcommand $SSH_ORIGINAL_COMMAND
fi

echo 'SSH authentication succeeded. Interactive login is not allowed.'
exit 1
