#!/bin/bash

# vim: set ts=4 sw=4:

if [ "$SSH_ORIGINAL_COMMAND" != "" ]; then
	case "$SSH_ORIGINAL_COMMAND" in
		"mango")
			cat "/var/local/mango/`whoami`" 2> /dev/null
			echo > "/var/local/mango/`whoami`" 2> /dev/null
			exit
			;;
	esac
fi

exit 1
