#!/bin/bash

# vim: set ts=4 sw=4:

if [ "$SSH_ORIGINAL_COMMAND" != "" ]; then
	case "$SSH_ORIGINAL_COMMAND" in
		"mango")
			exec sudo -n -g root /home/admin/bin/handle-ldap-modules reset-my-passwd
			;;
	esac
fi

exit 1
