#!/bin/bash

# Script to update the repository list for CGIT

# NOTE: This script is run via sudo to the gitadmin user. Using sudo constrains
#  the environment, but it's important to be a bit careful about what we do
#  in here.

BINDIR=/home/admin/gitadmin-bin

if [ `whoami` != gitadmin ] ; then
    cd / && exec sudo -u gitadmin $BINDIR/update-cgit "$@"
fi

echo -n "Updating the cgit repository list... "
$BINDIR/find-cgit-repos > /git/cgit.repositories
echo "done"
